import { AddFormProvider } from "../contexts/AddFormContext";
import "./globals.css";

import { Header } from "@/components/layout/Header";

export const metadata = {
  title: "todo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className={`max-w-6xl mx-auto bg-linear-to-r from-indigo-600 to-purple-700`}
      >
        <Header />
        <AddFormProvider>{children}</AddFormProvider>
      </body>
    </html>
  );
}
